### ISSUE TITLE
AttributeError: 'document' object has no attribute 'findall'

### ISSUE THREAD

**Issue by JonZavialov** [pradyunsg/lutra#50]
Hello, I am brand new to sphinx and have never used it before but I have been given a very complicated sphinx project, and I am trying to port it over to Lutra. I installed Lutra with `pip install "lutra @ git+https://github.com/pradyunsg/lutra/"`, and edited my `conf.py` file. When trying to build the file, it fails with this traceback:

```plaintext
Traceback (most recent call last):
  File "C:\virtualenv\documentation\lib\site-packages\sphinx\cmd\build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "C:\virtualenv\documentation\lib\site-packages\sphinx\application.py", line 344, in build
    self.builder.build_update()
  File "C:\virtualenv\documentation\lib\site-packages\sphinx\builders\__init__.py", line 294, in build_update
    self.build(to_build,
  File "C:\virtualenv\documentation\lib\site-packages\sphinx\builders\__init__.py", line 358, in build
    self.write(docnames, list(updated_docnames), method)
  File "C:\virtualenv\documentation\lib\site-packages\sphinx\builders\__init__.py", line 532, in write
    self._write_serial(sorted(docnames))
  File "C:\virtualenv\documentation\lib\site-packages\sphinx\builders\__init__.py", line 539, in _write_serial
    doctree = self.env.get_and_resolve_doctree(docname, self)
  File "C:\virtualenv\documentation\lib\site-packages\sphinx\environment\__init__.py", line 535, in get_and_resolve_doctree
    self.apply_post_transforms(doctree, docname)
  File "C:\virtualenv\documentation\lib\site-packages\sphinx\environment\__init__.py", line 581, in apply_post_transforms
    transformer.apply_transforms()
  File "C:\virtualenv\documentation\lib\site-packages\sphinx\transforms\__init__.py", line 86, in apply_transforms
    super().apply_transforms()
  File "C:\virtualenv\documentation\lib\site-packages\docutils\transforms\__init__.py", line 171, in apply_transforms
    transform.apply(**kwargs)
  File "C:\virtualenv\documentation\lib\site-packages\sphinx\transforms\post_transforms\__init__.py", line 43, in apply
    self.run(**kwargs)
  File "C:\virtualenv\documentation\lib\site-packages\lutra\__init__.py", line 60, in run
    for node in list(self.document.findall(nodes.table)):
AttributeError: 'document' object has no attribute 'findall'
```

If I delete the `WrapTableAndMathInAContainerTransform.run` method in `__init__.py`, and replace it with `pass`, it builds correctly. How can I resolve this error?

**Comment by pradyunsg** [comment]
Hi there! This project isn't quite ready for use/prime-time just yet. The description of the project includes:

> [very WIP, do not use]

While I appreciate that you're trying to use this theme and take that as a compliment, I suggest holding off until this theme is on PyPI before trying to use it.

---

Getting a newer version of `docutils` (and, maybe, Sphinx) should resolve the issue that you're seeing though. :)
