### ISSUE TITLE
Error after pip install from git

### ISSUE THREAD

**Issue by vasilchenkosv** [pradyunsg/lutra#79]
Windows 10 Ru, Sphinx v8.1.3

pip install "lutra @ git+https://github.com/pradyunsg/lutra/"
  ...
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "C:\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "C:\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "V:\Tmp\pip-build-env-6q21_t5m\overlay\Lib\site-packages\sphinx_theme_builder\__init__.py", line 80, in prepare_metadata_for_build_wheel
          return _generate_metadata(project, destination=Path(metadata_directory))
        File "V:\Tmp\pip-build-env-6q21_t5m\overlay\Lib\site-packages\sphinx_theme_builder\_internal\distributions.py", line 132, in generate_metadata
          (dist_info / "METADATA").write_text(project.get_metadata_file_contents())
        File "C:\Python310\lib\pathlib.py", line 1155, in write_text
          return f.write(data)
        File "C:\Python310\lib\encodings\cp1251.py", line 19, in encode
          return codecs.charmap_encode(input,self.errors,encoding_table)[0]
      UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f389' in position 3914: character maps to <undefined>
      [end of output]
  ...

**Comment by webknjaz** [comment]
This seems like a terminal encoding misconfiguration on the caller's side, not something related to this project directly.
